apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
        - name: payment-api
          image: sandeepkjl143/payment-image:latest
